SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `harstorage` ;
CREATE SCHEMA IF NOT EXISTS `harstorage` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `harstorage` ;

-- -----------------------------------------------------
-- Table `harstorage`.`URLS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `harstorage`.`URLS` ;

CREATE  TABLE IF NOT EXISTS `harstorage`.`URLS` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `URL` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `URL_UNIQUE` ON `harstorage`.`URLS` (`URL` ASC) ;


-- -----------------------------------------------------
-- Table `harstorage`.`PAGESPEED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `harstorage`.`PAGESPEED` ;

CREATE  TABLE IF NOT EXISTS `harstorage`.`PAGESPEED` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `SCORE` TINYINT UNSIGNED NOT NULL ,
  `AVOID_IMPORT` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Avoid CSS @import' ,
  `AVOID_BAD_REQ` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Avoid bad requests' ,
  `COMBINE_IMAGES` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Combine images into CSS sprites' ,
  `DEFER_LOAD_JS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Defer loading of JavaScript' ,
  `DEFER_PARS_JS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Defer parsing of JavaScript' ,
  `ENABLE_KEEPALIVE` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Enable Keep-Alive' ,
  `ENABLE_GZIP` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Enable compression' ,
  `INLINE_CSS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Inline Small CSS' ,
  `INLINE_JS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Inline Small JavaScript' ,
  `LEVERAGE_CACHE` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Leverage browser caching' ,
  `MAKE_REDIRECTS_CACHEABLE` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Make landing page redirects cacheable' ,
  `MINIFY_CSS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Minify CSS' ,
  `MINIFY_HTML` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Minify HTML' ,
  `MINIFY_JS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Minify JavaScript' ,
  `MINIMIZE_REDIRECTS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Minimize redirects' ,
  `MINIMIZE_REQ_SIZE` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Minimize request size' ,
  `OPTIMIZE_IMAGES` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Optimize images' ,
  `OPTIMIZE_ORDER` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Optimize the order of styles and scripts' ,
  `PREFER_ASYNC` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Prefer asynchronous resources' ,
  `PUT_CSS_IN_HEAD` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Put CSS in the document head' ,
  `REMOVE_QUERY_STRING` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Remove query strings from static resources' ,
  `REMOVE_UNUSED_CSS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT '	Remove unused CSS' ,
  `SERVE_FROM_CONSISTENT_URL` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Serve resources from a consistent URL' ,
  `SERVE_SCALED_IMAGES` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Serve scaled images' ,
  `SPECIFY_VARY` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT '	Specify a Vary: Accept-Encoding header' ,
  `SPECIFY_CACHE_VALIDATOR` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Specify a cache validator' ,
  `SPECIFY_CHAR_SET` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Specify a character set' ,
  `USE_EFFICIENT_SELECTORS` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Use efficient CSS selectors' ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `harstorage`.`LABELS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `harstorage`.`LABELS` ;

CREATE  TABLE IF NOT EXISTS `harstorage`.`LABELS` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `LABEL` VARCHAR(255) NOT NULL ,
  `LAST_METRIC` INT NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `harstorage`.`TESTRESULTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `harstorage`.`TESTRESULTS` ;

CREATE  TABLE IF NOT EXISTS `harstorage`.`TESTRESULTS` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `TIMESTAMP` TIMESTAMP NOT NULL ,
  `URL_ID` INT NOT NULL ,
  `LABEL_ID` INT NOT NULL ,
  `PAGESPEED_ID` INT NOT NULL ,
  `REQUESTS` MEDIUMINT NOT NULL ,
  `SIZE` MEDIUMINT NOT NULL ,
  `TIME` MEDIUMINT NOT NULL ,
  `HAR_KEY` CHAR(24) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `harstorage`.`TESTRESULTS` (`ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `harstorage`.`PAGESPEED`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
USE `harstorage`;
INSERT INTO `harstorage`.`PAGESPEED` (`SCORE`, `AVOID_IMPORT`, `AVOID_BAD_REQ`, `COMBINE_IMAGES`, `DEFER_LOAD_JS`, `DEFER_PARS_JS`, `ENABLE_KEEPALIVE`, `ENABLE_GZIP`, `INLINE_CSS`, `INLINE_JS`, `LEVERAGE_CACHE`, `MAKE_REDIRECTS_CACHEABLE`, `MINIFY_CSS`, `MINIFY_HTML`, `MINIFY_JS`, `MINIMIZE_REDIRECTS`, `MINIMIZE_REQ_SIZE`, `OPTIMIZE_IMAGES`, `OPTIMIZE_ORDER`, `PREFER_ASYNC`, `PUT_CSS_IN_HEAD`, `REMOVE_QUERY_STRING`, `REMOVE_UNUSED_CSS`, `SERVE_FROM_CONSISTENT_URL`, `SERVE_SCALED_IMAGES`, `SPECIFY_VARY`, `SPECIFY_CACHE_VALIDATOR`, `SPECIFY_CHAR_SET`, `USE_EFFICIENT_SELECTORS`) VALUES (100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100);
COMMIT;

COMMIT;
